baseURL = "http://localhost/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

[params]
  author = "Kashi"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
