baseURL = "http://localhost/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

[params]
  author = "Your Name"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
